#!/bin/bash
# =============================================================================
# Batched inference for Re-DMD β=2 + TAEW audio-fix training run.
# One Python process per (ckpt, GPU) — model + LoRA + VAE + wav2vec load ONCE,
# then loop over all 33 HDTF samples via inference_causal.py --input_dir.
#
# Expected wall time: ~55-60 min per GPU vs ~110 min for the per-video variant.
# --skip_existing means any video already generated by the earlier per-video
# run (5 clips per ckpt) is reused — no duplicate work.
#
# Staging dir layout (produced by the wrapper below):
#   /tmp/hdtf_staging/{name}/sub_clip.mp4 (symlink) + audio.wav (16k mono)
#
# Usage:
#   nohup bash scripts/infer_redmd_taew_audiofix_batched.sh > /tmp/infer_redmd_taew_audiofix_batched.log 2>&1 &
# =============================================================================
set -uo pipefail

CKPT_DIR="/tmp/FASTGEN_SF_OUTPUT_BETA2_AUDIOFIX_TAEW/OmniAvatar-FastGen/omniavatar_sf_audiofix/sf_sink1_window7_redmd_audiofix_beta2_taew/checkpoints"
OUT_ROOT="/home/work/output_hdtf_sf_redmd_beta2_taew"
STAGE_DIR="/tmp/hdtf_staging"

CKPT_STEPS=(${CKPT_STEPS:-100 200 300 400})
GPUS=(${GPUS:-0 1 2 3})

if [ ! -d "$STAGE_DIR" ] || [ "$(ls -d "$STAGE_DIR"/*/ 2>/dev/null | wc -l)" -lt 1 ]; then
    echo "ERROR: $STAGE_DIR not populated. Run the staging step first." >&2
    exit 1
fi
if [ "${#CKPT_STEPS[@]}" -ne "${#GPUS[@]}" ]; then
    echo "ERROR: CKPT_STEPS (${#CKPT_STEPS[@]}) and GPUS (${#GPUS[@]}) must match." >&2
    exit 1
fi

export OMNIAVATAR_ROOT="${OMNIAVATAR_ROOT:-/home/work/.local/OmniAvatar}"
N_SAMPLES=$(ls -d "$STAGE_DIR"/*/ | wc -l)

echo "============================================="
echo "  Re-DMD β=2 TAEW (audiofix) — Batched Inference"
echo "============================================="
echo "  CKPT_DIR:   $CKPT_DIR"
echo "  STAGE_DIR:  $STAGE_DIR ($N_SAMPLES samples)"
echo "  OUT_ROOT:   $OUT_ROOT"
echo "  Assignment:"
for i in "${!CKPT_STEPS[@]}"; do
    step="${CKPT_STEPS[$i]}"
    gpu="${GPUS[$i]}"
    step_p=$(printf "%07d" "$step")
    ckpt="$CKPT_DIR/${step_p}.pth"
    echo "    GPU ${gpu}: step ${step}  ->  ${ckpt}"
    [ -f "$ckpt" ] || { echo "    ERROR: ckpt missing: $ckpt" >&2; exit 1; }
    [ -d "$CKPT_DIR/${step_p}.net_model" ] || { echo "    ERROR: distcp dir missing" >&2; exit 1; }
done
echo "============================================="
echo ""

run_ckpt() {
    local GPU_ID=$1
    local STEP=$2
    local STEP_P=$(printf "%07d" "$STEP")
    local CKPT="$CKPT_DIR/${STEP_P}.pth"
    local OUT_DIR="$OUT_ROOT/step_${STEP_P}"
    mkdir -p "$OUT_DIR"

    local have=$(ls "$OUT_DIR"/*.mp4 2>/dev/null | grep -v aligned | wc -l)
    echo "[GPU $GPU_ID | step $STEP] Starting (${have}/${N_SAMPLES} already done from prior run; --skip_existing will reuse)"

    CUDA_VISIBLE_DEVICES=$GPU_ID /home/work/.local/miniconda3/envs/hb_fastgen/bin/python \
        scripts/inference/inference_causal.py \
        --ckpt_path "$CKPT" \
        --vae_path "$OMNIAVATAR_ROOT/pretrained_models/Wan2.1-T2V-1.3B/Wan2.1_VAE.pth" \
        --wav2vec_path "$OMNIAVATAR_ROOT/pretrained_models/wav2vec2-base-960h" \
        --mask_path /home/work/.local/Self-Forcing_LipSync_StableAvatar/diffsynth/utils/mask.png \
        --base_model_paths "$OMNIAVATAR_ROOT/pretrained_models/Wan2.1-T2V-1.3B/diffusion_pytorch_model.safetensors" \
        --omniavatar_ckpt_path /home/work/output_omniavatar_v2v_1.3B_phase2/step-19500.pt \
        --text_embeds_path /home/work/stableavatar_data/v2v_training_data/0010234f331f491ffacc538958094732_shot_001_000/text_emb.pt \
        --input_dir "$STAGE_DIR" \
        --output_dir "$OUT_DIR" \
        --skip_existing \
        --t_list 0.999 0.833 0.0 \
        --local_attn_size 7 \
        --sink_size 1 \
        --use_dynamic_rope \
        --latentsync \
        --face_cache_dir /home/work/.local/HDTF/face_cache \
    && echo "[GPU $GPU_ID | step $STEP] DONE" \
    || echo "[GPU $GPU_ID | step $STEP] FAILED (see log for stack trace)"
}

for i in "${!CKPT_STEPS[@]}"; do
    run_ckpt "${GPUS[$i]}" "${CKPT_STEPS[$i]}" &
done
wait

echo ""
echo "============================================="
echo "  Batched inference complete."
echo "============================================="
