#!/usr/bin/env python3
"""End-to-end verification of all three training paths with real data and real models.

Tests:
1. ODE KD (Stage 1a): 1.3B causal student on real ODE trajectories
2. Diffusion Forcing (Stage 1b): 1.3B causal student on real video data
3. Self-Forcing DMD (Stage 2): 14B teacher + 1.3B fake_score + 1.3B causal student

Run: CUDA_VISIBLE_DEVICES=2 python scripts/test_e2e_real_data.py
"""

import gc
import os
import sys
import time
import traceback

import torch
import torch.nn.functional as F

DEVICE = torch.device("cuda")
DTYPE = torch.bfloat16

OMNIAVATAR_ROOT = "/home/work/.local/OmniAvatar"
DATA_ROOT = "/home/work/stableavatar_data/v2v_training_data"
DATA_LIST = f"{DATA_ROOT}/video_square_path.txt"
MASK_PATH = "/home/work/.local/Self-Forcing_LipSync_StableAvatar/diffsynth/utils/mask.png"
TEACHER_CKPT = "/home/work/output_omniavatar_v2v_maskall_refseq_new_data_loss_weights_mouth_weights/step-1500.pt"
BASE_14B = ",".join(
    f"{OMNIAVATAR_ROOT}/pretrained_models/Wan2.1-T2V-14B/diffusion_pytorch_model-0000{i}-of-00006.safetensors"
    for i in range(1, 7)
)
BASE_1_3B = f"{OMNIAVATAR_ROOT}/pretrained_models/Wan2.1-T2V-1.3B/diffusion_pytorch_model.safetensors"


def gpu_mem():
    return torch.cuda.memory_allocated(DEVICE) / 1024**3


def gpu_peak():
    return torch.cuda.max_memory_allocated(DEVICE) / 1024**3


def print_header(msg):
    print(f"\n{'='*70}")
    print(f"  {msg}")
    print(f"{'='*70}")


def load_real_sample(need_path=False):
    """Load one real sample from the dataset.

    When need_path=True, looks for samples with ode_path.pt (our script's output).
    """
    from fastgen.datasets.omniavatar_dataloader import OmniAvatarDataset

    ds = OmniAvatarDataset(
        data_list_path=DATA_LIST,
        latentsync_mask_path=MASK_PATH,
        use_ref_sequence=True,
        load_ode_path=need_path,
    )

    # Find a sample (with ode_path.pt if needed)
    for i in range(min(len(ds), 100)):
        sample = ds[i]
        if sample is None:
            continue
        if need_path and "path" not in sample:
            continue
        # Move to device
        batch = {}
        for k, v in sample.items():
            if isinstance(v, torch.Tensor):
                batch[k] = v.unsqueeze(0).to(DEVICE)
            else:
                batch[k] = v
        sample_name = ds.dirs[i].split("/")[-1]
        print(f"  Loaded sample {i}: {sample_name}")
        for k, v in batch.items():
            if isinstance(v, torch.Tensor):
                print(f"    {k}: {v.shape} {v.dtype}")
        if need_path:
            # Verify it's from our script (ode_path.pt, not path.pth)
            import os
            ode_file = os.path.join(ds.dirs[i], "ode_path.pt")
            if os.path.exists(ode_file):
                print(f"    Source: ode_path.pt (our generation script)")
            else:
                print(f"    Source: path.pth (reference repo — fallback)")
        return batch

    raise RuntimeError("Could not find suitable sample" + (" with ODE path" if need_path else ""))


def build_condition(data):
    """Build OmniAvatar condition dict from data batch."""
    real = data["real"]
    ref_latent = real[:, :, :1, :, :]
    mask = data["mask"]
    if mask.dim() == 3:
        mask = mask[0]

    condition = {
        "text_embeds": data["text_embeds"].squeeze(1) if data["text_embeds"].dim() == 4 else data["text_embeds"],
        "audio_emb": data["audio_emb"],
        "ref_latent": ref_latent,
        "mask": mask,
        "masked_video": data["masked_video"],
    }
    if "ref_sequence" in data:
        condition["ref_sequence"] = data["ref_sequence"]
    return condition


# ============================================================
# TEST 1: ODE KD with ODE trajectories generated by OUR script
# ============================================================
def test_ode_kd():
    print_header("TEST 1: ODE KD — 1.3B causal student on ODE trajectories (from our generation script)")
    torch.cuda.reset_peak_memory_stats(DEVICE)

    from fastgen.networks.OmniAvatar.network_causal import CausalOmniAvatarWan

    # Load real sample WITH our generated ODE path (ode_path.pt)
    data = load_real_sample(need_path=True)
    assert "path" in data, "No ode_path.pt found! Run generate_omniavatar_ode_pairs.py first."
    print(f"  path shape: {data['path'].shape}, dtype: {data['path'].dtype}")

    condition = build_condition(data)

    # Build 1.3B causal student
    print("\n  Building 1.3B causal student for KD training...")
    student = CausalOmniAvatarWan(
        model_size="1.3B",
        in_dim=65,
        mode="v2v",
        use_audio=True,
        audio_hidden_size=32,
        chunk_size=3,
        total_num_frames=21,
        base_model_paths=BASE_1_3B,
        omniavatar_ckpt_path=None,
        net_pred_type="flow",
        schedule_type="rf",
    )
    student = student.to(device=DEVICE, dtype=DTYPE)
    student.train()
    print(f"  Student loaded: {gpu_mem():.1f} GB")

    # Simulate CausalKDModel.single_train_step logic
    ode_path = data["path"]  # [1, 4, 16, 21, 64, 64]
    real_data = data["real"]
    B, num_frames = ode_path.shape[0], ode_path.shape[3]
    chunk_size = student.chunk_size

    # Sample inhomogeneous timesteps
    t_inhom, ids = student.noise_scheduler.sample_t_inhom(
        B, num_frames, chunk_size,
        sample_steps=4,
        t_list=[0.999, 0.937, 0.833, 0.624, 0.0],
        device=DEVICE,
        dtype=ode_path.dtype,
    )
    print(f"  t_inhom: {t_inhom.shape}, sample: {t_inhom[0,:9].tolist()}")

    # Gather from path
    expand_shape = [ids.shape[0], 1, 1, ids.shape[1]] + [1] * max(0, ode_path.ndim - 4)
    ids_exp = ids.view(expand_shape).expand(-1, -1, *ode_path.shape[2:])
    denoise_path_all = torch.cat([ode_path, real_data.unsqueeze(1)], dim=1)
    noisy_data = torch.gather(denoise_path_all, 1, ids_exp).squeeze(1)
    print(f"  noisy_data: {noisy_data.shape}")

    # Student forward (full-sequence with inhomogeneous t)
    gen_data = student(noisy_data, t_inhom, condition=condition, fwd_pred_type="x0", is_ar=False)
    print(f"  gen_data: {gen_data.shape}")

    # L2 loss + backward
    loss = 0.5 * F.mse_loss(gen_data, real_data, reduction="mean")
    loss.backward()

    grad_count = sum(1 for p in student.parameters() if p.grad is not None)
    print(f"\n  Loss: {loss.item():.6f}")
    print(f"  Params with gradients: {grad_count}")
    print(f"  Peak memory: {gpu_peak():.1f} GB")
    print(f"  TEST 1 PASSED!")

    del student, gen_data, noisy_data, data
    gc.collect()
    torch.cuda.empty_cache()
    return True


# ============================================================
# TEST 2: Diffusion Forcing on real video data
# ============================================================
def test_diffusion_forcing():
    print_header("TEST 2: Diffusion Forcing — 1.3B causal student on real video data")
    torch.cuda.reset_peak_memory_stats(DEVICE)

    from fastgen.networks.OmniAvatar.network_causal import CausalOmniAvatarWan

    # Load real sample (no ODE path needed)
    data = load_real_sample(need_path=False)

    # Build student
    print("\n  Building 1.3B causal student...")
    student = CausalOmniAvatarWan(
        model_size="1.3B",
        in_dim=65,
        mode="v2v",
        use_audio=True,
        audio_hidden_size=32,
        chunk_size=3,
        total_num_frames=21,
        base_model_paths=BASE_1_3B,
        omniavatar_ckpt_path=None,
        net_pred_type="flow",
        schedule_type="rf",
    )
    student = student.to(device=DEVICE, dtype=DTYPE)
    student.train()
    print(f"  Student loaded: {gpu_mem():.1f} GB")

    condition = build_condition(data)
    real_data = data["real"]
    B, num_frames = real_data.shape[0], real_data.shape[2]
    chunk_size = student.chunk_size

    # Sample inhomogeneous timesteps (diffusion forcing)
    t_inhom, _ = student.noise_scheduler.sample_t_inhom(
        B, num_frames, chunk_size,
        sample_steps=4,
        t_list=[0.999, 0.937, 0.833, 0.624, 0.0],
        device=DEVICE,
        dtype=real_data.dtype,
    )
    print(f"  t_inhom: {t_inhom.shape}")

    # Add noise to real data (NOT ODE path)
    eps = torch.randn_like(real_data)
    t_inhom_expanded = t_inhom[:, None, :, None, None]
    noisy_data = student.noise_scheduler.forward_process(real_data, eps, t_inhom_expanded)
    print(f"  noisy_data: {noisy_data.shape}")

    # Student forward
    gen_data = student(noisy_data, t_inhom, condition=condition, fwd_pred_type="x0", is_ar=False)
    print(f"  gen_data: {gen_data.shape}")

    # L2 loss + backward
    loss = 0.5 * F.mse_loss(gen_data, real_data, reduction="mean")
    loss.backward()

    grad_count = sum(1 for p in student.parameters() if p.grad is not None)
    print(f"\n  Loss: {loss.item():.6f}")
    print(f"  Params with gradients: {grad_count}")
    print(f"  Peak memory: {gpu_peak():.1f} GB")
    print(f"  TEST 2 PASSED!")

    del student, gen_data, noisy_data, data
    gc.collect()
    torch.cuda.empty_cache()
    return True


# ============================================================
# TEST 3: Self-Forcing DMD with real teacher/student/fake_score
# ============================================================
def test_self_forcing_dmd():
    print_header("TEST 3: Self-Forcing DMD — 14B teacher + 1.3B fake_score + 1.3B student")
    torch.cuda.reset_peak_memory_stats(DEVICE)

    from fastgen.networks.OmniAvatar.network import OmniAvatarWan
    from fastgen.networks.OmniAvatar.network_causal import CausalOmniAvatarWan

    # Load real sample
    data = load_real_sample(need_path=False)
    condition = build_condition(data)
    neg_condition = {
        "text_embeds": data["neg_text_embeds"].squeeze(1) if data["neg_text_embeds"].dim() == 4 else data["neg_text_embeds"],
        "audio_emb": torch.zeros_like(data["audio_emb"]),
        "ref_latent": condition["ref_latent"],
        "mask": condition["mask"],
        "masked_video": condition["masked_video"],
    }
    if "ref_sequence" in condition:
        neg_condition["ref_sequence"] = condition["ref_sequence"]

    real_data = data["real"]

    # --- Load 14B teacher ---
    print("\n  Loading 14B teacher (bidirectional)...")
    t0 = time.time()
    teacher = OmniAvatarWan(
        model_size="14B",
        in_dim=65,
        mode="v2v",
        use_audio=True,
        audio_hidden_size=32,
        base_model_paths=BASE_14B,
        omniavatar_ckpt_path=TEACHER_CKPT,
        merge_lora=True,
        net_pred_type="flow",
        schedule_type="rf",
    )
    teacher = teacher.to(device=DEVICE, dtype=DTYPE)
    teacher.eval().requires_grad_(False)
    print(f"  Teacher loaded: {gpu_mem():.1f} GB ({time.time()-t0:.0f}s)")

    # --- Load 1.3B fake_score ---
    print("  Loading 1.3B fake_score (bidirectional)...")
    fake_score = OmniAvatarWan(
        model_size="1.3B",
        in_dim=65,
        mode="v2v",
        use_audio=True,
        audio_hidden_size=32,
        base_model_paths=BASE_1_3B,
        omniavatar_ckpt_path=None,
        net_pred_type="flow",
        schedule_type="rf",
    )
    fake_score = fake_score.to(device=DEVICE, dtype=DTYPE)
    fake_score.eval().requires_grad_(False)
    print(f"  Fake score loaded: {gpu_mem():.1f} GB")

    # --- Load 1.3B causal student ---
    print("  Loading 1.3B causal student...")
    student = CausalOmniAvatarWan(
        model_size="1.3B",
        in_dim=65,
        mode="v2v",
        use_audio=True,
        audio_hidden_size=32,
        chunk_size=3,
        total_num_frames=21,
        base_model_paths=BASE_1_3B,
        omniavatar_ckpt_path=None,
        net_pred_type="flow",
        schedule_type="rf",
    )
    student = student.to(device=DEVICE, dtype=DTYPE)
    student.train()
    print(f"  Student loaded: {gpu_mem():.1f} GB")
    print(f"  All 3 models in memory: {gpu_mem():.1f} GB")

    # --- Self-Forcing rollout (all 7 chunks, gradient on last 2) ---
    num_frames = real_data.shape[2]
    print(f"\n  Running Self-Forcing rollout (all {num_frames // student.chunk_size} chunks, gradient on last 2)...")
    student.clear_caches()

    B = real_data.shape[0]
    chunk_size = student.chunk_size
    num_blocks = num_frames // chunk_size
    noise = torch.randn_like(real_data)
    noise = student.noise_scheduler.latents(noise=noise)  # scale by sigma_max

    t_list = torch.tensor([0.999, 0.937, 0.833, 0.624, 0.0], device=DEVICE, dtype=torch.float64)
    denoised_blocks = []

    for block_idx in range(num_blocks):
        cur_start_frame = 0 if block_idx == 0 else chunk_size * block_idx
        cur_end_frame = chunk_size * (block_idx + 1)
        noisy_input = noise[:, :, cur_start_frame:cur_end_frame]

        # Denoise: exit at random step
        exit_step = torch.randint(0, 4, (1,)).item()
        for step in range(len(t_list) - 1):
            t_cur = t_list[step].expand(B)
            if step == exit_step:
                # Exit step: with gradient on last 2 chunks only
                enable_grad = block_idx >= num_blocks - 2
                with torch.set_grad_enabled(enable_grad):
                    x0_pred = student(
                        noisy_input, t_cur, condition=condition,
                        fwd_pred_type="x0", cur_start_frame=cur_start_frame,
                        store_kv=False, is_ar=True,
                    )
                break
            else:
                with torch.no_grad():
                    x0_pred = student(
                        noisy_input, t_cur, condition=condition,
                        fwd_pred_type="x0", cur_start_frame=cur_start_frame,
                        store_kv=False, is_ar=True,
                    )
                t_next = t_list[step + 1].expand(B)
                eps_infer = torch.randn_like(x0_pred)
                noisy_input = student.noise_scheduler.forward_process(x0_pred, eps_infer, t_next)

        denoised_blocks.append(x0_pred)

        # Cache update (no grad)
        with torch.no_grad():
            t_zero = torch.zeros(B, device=DEVICE, dtype=DTYPE)
            _ = student(
                x0_pred, t_zero, condition=condition,
                fwd_pred_type="x0", cur_start_frame=cur_start_frame,
                store_kv=True, is_ar=True,
            )

    gen_data = torch.cat(denoised_blocks, dim=2)
    print(f"  Rollout output: {gen_data.shape}")
    print(f"  Memory after rollout: {gpu_mem():.1f} GB")

    # --- VSD loss with teacher ---
    print("  Computing VSD loss with teacher...")
    t_vsd = student.noise_scheduler.sample_t(
        B, time_dist_type="shifted", min_t=0.001, max_t=0.999, device=DEVICE
    )
    eps_vsd = torch.randn_like(gen_data)
    perturbed = student.noise_scheduler.forward_process(gen_data, eps_vsd, t_vsd)

    with torch.no_grad():
        # Teacher prediction (on gen_data subset matching rollout)
        teacher_x0 = teacher(perturbed, t_vsd, condition=condition, fwd_pred_type="x0")
        print(f"  Teacher x0: {teacher_x0.shape}")

        # Fake score prediction
        fake_x0 = fake_score(perturbed, t_vsd, condition=condition, fwd_pred_type="x0")
        print(f"  Fake score x0: {fake_x0.shape}")

    # VSD loss
    w = 1.0 / (torch.abs(gen_data - teacher_x0.detach()) + 1e-6)
    vsd_grad = (fake_x0.detach() - teacher_x0.detach()) * w
    pseudo_target = gen_data - vsd_grad
    vsd_loss = 0.5 * F.mse_loss(gen_data, pseudo_target.detach(), reduction="mean")

    print(f"\n  VSD loss: {vsd_loss.item():.6f}")

    # Backward
    vsd_loss.backward()
    grad_count = sum(1 for p in student.parameters() if p.grad is not None)
    print(f"  Student params with gradients: {grad_count}")

    # --- Fake score DSM update (separate step — free student graph first) ---
    print("\n  Testing fake score DSM update...")
    # In real training, this is a separate iteration (student_update_freq).
    # Free everything from the student update to reclaim memory.
    gen_data_for_dsm = gen_data.detach().clone()
    student.zero_grad(set_to_none=True)
    del vsd_loss, pseudo_target, vsd_grad, w, gen_data, denoised_blocks, noise
    del teacher_x0, fake_x0, perturbed, eps_vsd
    try:
        del teacher_x0_cfg, teacher_x0_neg
    except NameError:
        pass
    # Free teacher — not needed for DSM loss (only fake_score + gen_data)
    del teacher
    eps_vsd = torch.randn(1, 16, 21, 64, 64, device=DEVICE, dtype=DTYPE)  # fresh noise for DSM
    gc.collect()
    torch.cuda.empty_cache()
    print(f"  Memory after cleanup: {gpu_mem():.1f} GB")

    fake_score.train().requires_grad_(True)
    student.eval().requires_grad_(False)

    with torch.no_grad():
        x_t_sg = student.noise_scheduler.forward_process(gen_data_for_dsm, eps_vsd, t_vsd)

    fake_pred = fake_score(x_t_sg, t_vsd, condition=condition, fwd_pred_type="x0")
    dsm_loss = F.mse_loss(fake_pred, gen_data_for_dsm, reduction="mean")
    dsm_loss.backward()

    fs_grad_count = sum(1 for p in fake_score.parameters() if p.grad is not None)
    print(f"  DSM loss: {dsm_loss.item():.6f}")
    print(f"  Fake score params with gradients: {fs_grad_count}")

    # --- CFG with neg_condition ---
    print("\n  Testing CFG with negative condition...")
    with torch.no_grad():
        teacher_x0_neg = teacher(perturbed, t_vsd, condition=neg_condition, fwd_pred_type="x0")
    teacher_x0_cfg = teacher_x0 + 4.5 * (teacher_x0 - teacher_x0_neg)
    print(f"  CFG teacher x0: {teacher_x0_cfg.shape}, range [{teacher_x0_cfg.min():.3f}, {teacher_x0_cfg.max():.3f}]")

    print(f"\n  Peak memory: {gpu_peak():.1f} GB")
    print(f"  TEST 3 PASSED!")

    student.clear_caches()
    del teacher, fake_score, student, gen_data
    gc.collect()
    torch.cuda.empty_cache()
    return True


# ============================================================
# MAIN
# ============================================================
if __name__ == "__main__":
    print(f"GPU: {torch.cuda.get_device_name(DEVICE)}")
    print(f"Free memory: {torch.cuda.mem_get_info(DEVICE)[0]/1024**3:.1f} GB")

    results = {}

    try:
        results["ODE KD"] = test_ode_kd()
    except Exception as e:
        print(f"\n  TEST 1 FAILED: {e}")
        traceback.print_exc()
        results["ODE KD"] = False
        gc.collect()
        torch.cuda.empty_cache()

    try:
        results["Diffusion Forcing"] = test_diffusion_forcing()
    except Exception as e:
        print(f"\n  TEST 2 FAILED: {e}")
        traceback.print_exc()
        results["Diffusion Forcing"] = False
        gc.collect()
        torch.cuda.empty_cache()

    try:
        results["Self-Forcing DMD"] = test_self_forcing_dmd()
    except Exception as e:
        print(f"\n  TEST 3 FAILED: {e}")
        traceback.print_exc()
        results["Self-Forcing DMD"] = False
        gc.collect()
        torch.cuda.empty_cache()

    print_header("RESULTS SUMMARY")
    all_passed = True
    for name, passed in results.items():
        status = "PASSED" if passed else "FAILED"
        print(f"  {name}: {status}")
        if not passed:
            all_passed = False

    print()
    if all_passed:
        print("  ALL 3 TESTS PASSED!")
    else:
        print("  SOME TESTS FAILED — see details above")
        sys.exit(1)
