#!/bin/bash
# =============================================================================
# SF Re-DMD β=2 TAEW audiofix — fsmatched + lr3e6 — DF-500 init variant
# =============================================================================
#
# Same as train_sf_sink1_window7_redmd_beta2_audiofix_taew_syncnet_mouthweight_fsmatched.sh
# (syncnet DF init + mouthweight 14B teacher + fsmatched fake score + critic lr 3e-6)
# with a SINGLE difference: the DF student init is the step-500 ckpt of the
# syncnet-trained DF run instead of the step-5000 final ckpt.
#
# Rationale: the original 5000-iter DF run's intermediate checkpoints were
# deleted; we regenerated only step-500 via
# train_omniavatar_df_shift_5_audiofix_syncnet_trained_500iter.sh. This SF
# variant uses that step-500 ckpt to explore how earlier-stage DF
# distillation affects the final SF student.
#
# Distinct output dir + wandb run name (_df500 suffix) so this doesn't
# collide with the DF-5000 variant's run 1djswvuo.
#
# Usage:
#   bash scripts/train_sf_sink1_window7_redmd_beta2_audiofix_taew_syncnet_mouthweight_fsmatched_df500.sh
#
# Resume (same wandb run via persisted wandb_id.txt):
#   RESUME=True bash scripts/train_sf_sink1_window7_redmd_beta2_audiofix_taew_syncnet_mouthweight_fsmatched_df500.sh
#
# Prereq: the DF step-500 ckpt must exist. Generated by:
#   bash scripts/train_omniavatar_df_shift_5_audiofix_syncnet_trained_500iter.sh
# =============================================================================

set -euo pipefail

# The parent script looks up these three envs with ${VAR:-default} so we
# can override them here and delegate everything else.

# DF init: step-500 of the 500-iter recovery run
export OMNIAVATAR_DF_CKPT="${OMNIAVATAR_DF_CKPT:-/home/work/.local/hyunbin/FastGen-redmd/FASTGEN_OUTPUT/OmniAvatar-FastGen/omniavatar_df_audiofix/df_audiofix_syncnet_trained_shift_5_4gpu_bs16_lr1e5_500iter/checkpoints/0000500.pth}"

# Distinct output dir and wandb run name (_df500 suffix)
export FASTGEN_OUTPUT_ROOT="${FASTGEN_OUTPUT_ROOT:-/tmp/FASTGEN_SF_OUTPUT_BETA2_AUDIOFIX_TAEW_SYNCNET_MOUTHWEIGHT_FSMATCHED_LR3E6_DF500}"
export RUN_NAME="${RUN_NAME:-sf_sink1_window7_redmd_audiofix_beta2_taew_syncnet_mouthweight_fsmatched_lr3e6_df500}"

# Delegate to the fsmatched parent; inherits teacher/student/fsmatched/lr3e6.
exec "$(dirname "$(readlink -f "$0")")/train_sf_sink1_window7_redmd_beta2_audiofix_taew_syncnet_mouthweight_fsmatched.sh" "$@"
